### ISSUE TITLE
error: Module not found "https://deno.land/std/encoding/utf8.ts".     at https://deno.land/x/bcrypt@v0.2.1/bcrypt/bcrypt.ts:1:24

### ISSUE THREAD

**Issue by miguelgargallo** [thecodeholic/deno-login-register#1]
user@macos deno-login-register % cp deno-login-register .env
cp: deno-login-register: No such file or directory
user@macos deno-login-register % cp deno-login-register /.env
cp: deno-login-register: No such file or directory
user@macos deno-login-register % cp .env.example .env
user@macos deno-login-register % deno run --allow-net --allow-read --allow-env server.ts
Download ⠼ https://deno.land/x/dotenv@v0.4.1/mod.ts                             Warning Implicitly using latest version (v2.7) for https://deno.land/x/djwt/validate.ts
Download ⠴ https://deno.land/x/dejs@0.7.0/vendor/https/deno.land/x/lodash/escape
Download ⠇ https://denopkg.com/chiefbiiko/hmac@master/mod.ts                    Warning Implicitly using latest version (0.158.0) for https://deno.land/std/encoding/hex.ts
Download ⠙ https://deno.land/x/lodash@4.17.15-es/_baseGetTag.js                 Warning Implicitly using latest version (0.158.0) for https://deno.land/std/encoding/utf8.ts
error: Module not found "https://deno.land/std/encoding/utf8.ts".
    at https://deno.land/x/bcrypt@v0.2.1/bcrypt/bcrypt.ts:1:24
user@macos deno-login-register %

**Comment by miguelgargallo** [comment]
Thanks for you time, and Merry Christmas 🎄
